// FunFacts/FunFacts.Web/ClientApp/src/components/NavMenu.tsx
import React, { useState } from "react";
import {
  Collapse,
  Container,
  Navbar,
  NavbarBrand,
  NavbarToggler,
  NavItem,
  NavLink,
} from "reactstrap";
import { Link } from "react-router-dom";
import "./NavMenu.css";

export const NavMenu = () => {
  // static displayName = NavMenu.name;

  const [collapsed, setCollapsed] = useState(true);

  const toggleNavbar = () => {
    setCollapsed((c) => !c);
  };

  return (
    <header>
      <Navbar
        className="navbar-expand-sm navbar-toggleable-sm ng-white border-bottom box-shadow mb-3"
        light
      >
        <Container>
          <NavbarBrand tag={Link} to="/">
            FunFacts
          </NavbarBrand>
          <NavbarToggler onClick={toggleNavbar} className="mr-2" />
          <Collapse
            className="d-sm-inline-flex flex-sm-row-reverse"
            isOpen={!collapsed}
            navbar
          >
            <ul className="navbar-nav flex-grow">
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/">
                  Home
                </NavLink>
              </NavItem>
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/counter">
                  Counter
                </NavLink>
              </NavItem>
              <NavItem>
                <NavLink tag={Link} className="text-dark" to="/fetch-data">
                  Fetch data
                </NavLink>
              </NavItem>
            </ul>
          </Collapse>
        </Container>
      </Navbar>
    </header>
  );
};

// TravelBug/TravelBug/ClientApp/src/app/nav-menu/nav-menu.component.ts
import { Component, OnInit } from "@angular/core";
import { AccountService } from "../services/account.service";
import { Subscription } from "rxjs";
import { Router } from "@angular/router";
import { FetchDataService } from "../services/fetch-data.service";

@Component({
  selector: "app-nav-menu",
  templateUrl: "./nav-menu.component.html",
  styleUrls: ["./nav-menu.component.css"],
})
export class NavMenuComponent implements OnInit {
  isExpanded = false;
  isLoggedIn: boolean;
  loginSub: Subscription;

  constructor(private accountService: AccountService, private router: Router, private fetchDataService: FetchDataService) {}

  ngOnInit() {
    this.isLoggedIn = this.accountService.hasToken;
    this.loginSub = this.accountService.loginStatus.subscribe((loginStatus) => {
      this.isLoggedIn = loginStatus;
    });
  }

  loadAndRedirect(route: string) {
    this.fetchDataService.fetchData(route);
  }

  collapse() {
    this.isExpanded = false;
  }

  toggle() {
    this.isExpanded = !this.isExpanded;
  }

  ngOnDestroy() {
    this.loginSub.unsubscribe();
  }
}

<header>
  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
      <a [routerLink]="['/']" class="navbar-brand">TravelBug</a>
      <button (click)="toggle()" [attr.aria-expanded]="isExpanded" aria-label="Toggle navigation" class="navbar-toggler" data-target=".navbar-collapse" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div [ngClass]="{ show: isExpanded }" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow">
          <li [routerLinkActiveOptions]="{ exact: true }" [routerLinkActive]="['link-active']" class="nav-item">

            <a [routerLink]="['/']" class="nav-link text-dark">Home</a>
          </li>
          <li [routerLinkActive]="['link-active']" class="nav-item">
            <a (click)="loadAndRedirect('/blogs')" [routerLink] class="nav-link text-dark">Blogs</a>
          </li>
          <li *ngIf="!isLoggedIn" [routerLinkActive]="['link-active']" class="nav-item">
            <a (click)="loadAndRedirect('/account')" [routerLink] class="nav-link text-dark">Sign up / login</a>
          </li>
          <li *ngIf="isLoggedIn" [routerLinkActive]="['link-active']" class="nav-item">
            <a (click)="loadAndRedirect('/profile')" [routerLink] class="nav-link text-dark">Profile</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
